name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '**' ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  macBuild:
    # macos-latest is currently macos-11 but i need macos-12
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Cache Nugets
    - uses: actions/cache@v3
      with:
        path: ~/.nuget/packages     
        key: ${{ runner.os }}-nuget11-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
            ${{ runner.os }}-nuget11-
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.6      
      with:
        nuget-version: latest
    # - name: Set default Xamarin SDK versions
    #   run: |
    #     $VM_ASSETS/select-xamarin-sdk-v2.sh --mono=6.12 --ios=14.14 --android=11.1
    # - name: Set default Xcode 12.4
    #   run: |
    #     XCODE_ROOT=/Applications/Xcode_12.4.app
    #     echo "MD_APPLE_SDK_ROOT=$XCODE_ROOT" >> $GITHUB_ENV
    #     sudo xcode-select -s $XCODE_ROOT
    - name: Setup Xcode version 14.0
      uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '14.0'
    # .Net 7 already installed on github actions        
    #- name: Setup .NET Core SDK
    #  uses: actions/setup-dotnet@v3
    #  with:
    #     dotnet-version: |
    #       7.0.100
    #     include-prerelease: false    
    - name: install maui macos android ios maccatalyst wasm-tools wasm-tools-net6
      run: dotnet workload install maui macos android ios maccatalyst wasm-tools wasm-tools-net6
    - name: Restore dependencies Legacy
      run: nuget restore Mapsui.Mac.Legacy.sln   
    - name: Restore dependencies Mapsui.Mac
      run: dotnet restore Mapsui.Mac.slnf       
    # Samples Build           
    - name: Build Mapsui.Samples.Droid
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Droid/Mapsui.Samples.Droid.csproj                       
    # Samples Forms    
    - name: Build Mapsui.Samples.Forms.Shared
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Shared/Mapsui.Samples.Forms.Shared.csproj    
    - name: Build Mapsui.Samples.Forms.Android
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Android/Mapsui.Samples.Forms.Android.csproj     
    - name: Build Mapsui.Samples.Forms.iOS
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.iOS/Mapsui.Samples.Forms.iOS.csproj     
    - name: Build Mapsui.Samples.Forms.Mac
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Mac/Mapsui.Samples.Forms.Mac.csproj    
    # Builds that need XCode 14.2
    # This works on Real Mac Devices but not on Github Actions, disable it for now (this is run on the Windows build)
    - name: Setup Xcode version 14.2
      uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: '14.2'
    - name: Build Mapsui.Samples.iOS
      run: dotnet build --no-restore --configuration Debug -r iossimulator-x64 --self-contained Samples/Mapsui.Samples.iOS/Mapsui.Samples.iOS.csproj
    # Samples Uno
    - name: Mapsui.Samples.Uno.Mobile
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Mobile/Mapsui.Samples.Uno.Mobile.csproj
    #- name: Mapsui.Samples.Uno.Skia.Gtk
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Skia.Gtk/Mapsui.Samples.Uno.Skia.Gtk.csproj
    #- name: Mapsui.Samples.Uno.Skia.Linux.FrameBuffer
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Skia.Linux.FrameBuffer/Mapsui.Samples.Uno.Skia.Linux.FrameBuffer.csproj
    #- name: Mapsui.Samples.Uno.Skia.Tizen
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Skia.Tizen/Mapsui.Samples.Uno.Skia.Tizen.csproj
    #- name: Mapsui.Samples.Uno.Skia.Wpf
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Skia.Wpf/Mapsui.Samples.Uno.Skia.Wpf.csproj
    #- name: Mapsui.Samples.Uno.UWP
    #  run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.UWP/Mapsui.Samples.Uno.UWP.csproj
    #- name: Mapsui.Samples.Uno.Wasm
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Wasm/Mapsui.Samples.Uno.Wasm.csproj
    # Samples Uno WinUI
    - name: Mapsui.Samples.Uno.WinUI.Mobile
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno.WinUI/Mapsui.Samples.Uno.WinUI.Mobile/Mapsui.Samples.Uno.WinUI.Mobile.csproj
    #- name: Mapsui.Samples.Uno.WinUI.Skia.Gtk
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno.WinUI/Mapsui.Samples.Uno.WinUI.Skia.Gtk/Mapsui.Samples.Uno.WinUI.Skia.Gtk.csproj
    #- name: Mapsui.Samples.Uno.WinUI.Skia.Linux.FrameBuffer
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno.WinUI/Mapsui.Samples.Uno.WinUI.Skia.Linux.FrameBuffer/Mapsui.Samples.Uno.WinUI.Skia.Linux.FrameBuffer.csproj
    #- name: Mapsui.Samples.Uno.WinUI.Skia.WPF
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno.WinUI/Mapsui.Samples.Uno.WinUI.Skia.WPF/Mapsui.Samples.Uno.WinUI.Skia.WPF.csproj
    #- name: Mapsui.Samples.Uno.WinUI.Wasm
    #  run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno.WinUI/Mapsui.Samples.Uno.WinUI.Wasm/Mapsui.Samples.Uno.WinUI.Wasm.csproj
    #- name: Mapsui.Samples.Uno.WinUI.Windows
    #  run: dotnet build --no-restore --configuration Debug  /p:Platform=x64 Samples/Mapsui.Samples.Uno.WinUI/Mapsui.Samples.Uno.WinUI.Windows/Mapsui.Samples.Uno.WinUI.Windows.csproj
    # Test Build    
    - name: Build Mapsui.Rendering.Skia.Tests
      run: dotnet build --no-restore --configuration Debug Tests/Mapsui.Rendering.Skia.Tests/Mapsui.Rendering.Skia.Tests.csproj
    - name: Build Mapsui.Tests
      run: dotnet build --no-restore --configuration Debug Tests/Mapsui.Tests/Mapsui.Tests.csproj    
    # Run Tests   
    - name: Run Mapsui.Rendering.Skia.Tests
      run: dotnet test Tests/Mapsui.Rendering.Skia.Tests/bin/Debug/net6.0/Mapsui.Rendering.Skia.Tests.dll    
    - name: Run Mapsui.Tests
      run: dotnet test Tests/Mapsui.Tests/bin/Debug/net6.0/Mapsui.Tests.dll
    # Release Build
    - name: Build Mapsui
      run: dotnet pack --no-restore --configuration Release Mapsui/Mapsui.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Build Mapsui.Rendering.Skia
      run: dotnet pack --no-restore --configuration Release Mapsui.Rendering.Skia/Mapsui.Rendering.Skia.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Build Mapsui.Tiling
      run: dotnet pack --no-restore --configuration Release Mapsui.Tiling/Mapsui.Tiling.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Build Mapsui.Nts
      run: dotnet pack --no-restore --configuration Release Mapsui.Nts/Mapsui.Nts.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Build Mapsui.ArcGIS
      run: dotnet pack --no-restore --configuration Release Mapsui.ArcGIS/Mapsui.ArcGIS.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Build Mapsui.Extensions
      run: dotnet pack --no-restore --configuration Release Mapsui.Extensions/Mapsui.Extensions.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Build Mapsui.UI.Android
      run: dotnet pack --no-restore --configuration Release Mapsui.UI.Android/Mapsui.UI.Android.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Build Mapsui.UI.iOS
      run: dotnet pack --no-restore --configuration Release Mapsui.UI.iOS/Mapsui.UI.iOS.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Build Mapsui.UI.Forms
      run: dotnet pack --no-restore --configuration Release Mapsui.UI.Forms/Mapsui.UI.Forms.csproj -o Artifacts -p:PackageVersion=$(git describe --tags)
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: nupkg.mac
        path: Artifacts/*.nupkg
  
  winBuild:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    # Cache Nugets
    - uses: actions/cache@v3
      with:
        path: |
          ~/.nuget/packages/Microsoft*
          ~/.nuget/packages/SkiaSharp* 
          ~/.nuget/packages/System*
          ~/.nuget/packages/Xamarin*
        key: ${{ runner.os }}-nuget10-${{ hashFiles('Directory.Packages.props') }}
        restore-keys: |
            ${{ runner.os }}-nuget10-
    # .Net 7 already installed on Github Actions      
    #- name: Setup .NET Core SDK
    #  uses: actions/setup-dotnet@v3
    #  with:
    #     dotnet-version: |
    #       7.0.100
    #     include-prerelease: false
    - name: Setup NuGet.exe for use with actions
      uses: NuGet/setup-nuget@v1.0.6
      with:
        nuget-version: latest
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-prerelease: true
    - name: install maui macos android ios maccatalyst wasm-tools wasm-tools-net6
      run: dotnet workload install maui macos android ios maccatalyst wasm-tools wasm-tools-net6
    - name: Restore dependencies
      run: .nuget\nuget restore Mapsui.sln     
    # Test Build
    - name: Mapsui.Nts.Tests
      run: dotnet build --no-restore --configuration Debug Tests/Mapsui.Nts.Tests/Mapsui.Nts.Tests.csproj
    - name: Mapsui.Rendering.Skia.Tests
      run: dotnet build --no-restore --configuration Debug Tests/Mapsui.Rendering.Skia.Tests/Mapsui.Rendering.Skia.Tests.csproj
    - name: Mapsui.Tests
      run: dotnet build --no-restore --configuration Debug Tests/Mapsui.Tests/Mapsui.Tests.csproj
    - name: Mapsui.UI.Forms.Tests
      run: dotnet build --no-restore --configuration Debug Mapsui.UI.Forms.Tests\Mapsui.UI.Forms.Tests.csproj
    # Test Run
    - name: Run Mapsui.Nts.Tests
      run: dotnet test Tests/Mapsui.Nts.Tests/bin/Debug/net6.0/Mapsui.Nts.Tests.dll
    - name: Run Mapsui.Rendering.Skia.Tests
      uses: nick-fields/retry@v2.7.0
      with:
        timeout_minutes: 10
        max_attempts: 3        
        command: dotnet test Tests/Mapsui.Rendering.Skia.Tests/bin/Debug/net6.0/Mapsui.Rendering.Skia.Tests.dll    
    - name: Run Mapsui.Tests
      run: dotnet test Tests/Mapsui.Tests/bin/Debug/net6.0/Mapsui.Tests.dll
    - name: Run Mapsui.UI.Forms.Tests
      run: dotnet test Mapsui.UI.Forms.Tests/bin/Debug/net6.0-windows10.0.19041.0/Mapsui.UI.Forms.Tests.dll
    # Release Build
    - name: Build nuget packages
      run: Scripts\buildpack $(git describe --tags)
    - name: Cleanup
      run: git clean -fx -d -e Artifacts
    # Change Project References to nuget package references in samples    
    - name: nuget ProjectReferences to PackageReferences
      shell: pwsh
      run: |
        ./Scripts/SamplesMapsuiNugetReferences.ps1        
    - name: Restore dependencies
      run: .nuget\nuget restore Mapsui.sln      
    # Samples Build 
    - name: Mapsui.Samples.Avalonia
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Avalonia/Mapsui.Samples.Avalonia.csproj
    - name: Mapsui.Samples.Blazor
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Blazor/Mapsui.Samples.Blazor.csproj
    - name: Mapsui.Samples.Droid
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Droid/Mapsui.Samples.Droid.csproj
    - name: Mapsui.Samples.Eto
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Eto/Mapsui.Samples.Eto.csproj
    - name: Mapsui.Samples.iOS
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.iOS/Mapsui.Samples.iOS.csproj
    - name: Mapsui.Samples.Maui
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Maui/Mapsui.Samples.Maui.csproj
    - name: Mapsui.Samples.Maui.MapView
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Maui.MapView/Mapsui.Samples.Maui.MapView.csproj
    - name: Mapsui.Samples.WinUI
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug -p:Platform=x86 Samples\Mapsui.Samples.WinUI\Mapsui.Samples.WinUI\Mapsui.Samples.WinUI.csproj
    - name: Mapsui.Samples.Wpf
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Wpf/Mapsui.Samples.Wpf.csproj
    - name: Mapsui.Samples.Wpf.Editing    
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Wpf.Editing/Mapsui.Samples.Wpf.Editing.csproj    
    # Samples Forms
    - name: Mapsui.Samples.Forms.Android
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Android/Mapsui.Samples.Forms.Android.csproj
    - name: Mapsui.Samples.Forms.iOS
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.iOS/Mapsui.Samples.Forms.iOS.csproj
    - name: Mapsui.Samples.Forms.Mac
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.Mac/Mapsui.Samples.Forms.Mac.csproj
    - name: Mapsui.Samples.Forms.UWP
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.UWP/Mapsui.Samples.Forms.UWP.csproj
    - name: Mapsui.Samples.Forms.WPF
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Forms/Mapsui.Samples.Forms.WPF/Mapsui.Samples.Forms.WPF.csproj
    # Samples Uno
    - name: Mapsui.Samples.Uno.Mobile
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Mobile/Mapsui.Samples.Uno.Mobile.csproj
    - name: Mapsui.Samples.Uno.Skia.Gtk
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Skia.Gtk/Mapsui.Samples.Uno.Skia.Gtk.csproj
    - name: Mapsui.Samples.Uno.Skia.Linux.FrameBuffer
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Skia.Linux.FrameBuffer/Mapsui.Samples.Uno.Skia.Linux.FrameBuffer.csproj
    - name: Mapsui.Samples.Uno.Skia.Tizen
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Skia.Tizen/Mapsui.Samples.Uno.Skia.Tizen.csproj
    - name: Mapsui.Samples.Uno.Skia.Wpf
      run: dotnet build --no-restore --configuration Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.Skia.Wpf/Mapsui.Samples.Uno.Skia.Wpf.csproj
    - name: Mapsui.Samples.Uno.UWP
      run: msbuild -p:RestorePackages=false -p:Configuration=Debug Samples/Mapsui.Samples.Uno/Mapsui.Samples.Uno.UWP/Mapsui.Samples.Uno.UWP.csproj
    - name: Mapsui.Samples.Uno.Wasm
      run: dotnet build --no-restore --configuration Debug Samples\Mapsui.Samples.Uno\Mapsui.Samples.Uno.Wasm\Mapsui.Samples.Uno.Wasm.csproj
    # Samples Uno WinUI
    - name: Mapsui.Samples.Uno.WinUI.Mobile
      run: dotnet build --no-restore --configuration Debug Samples\Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Mobile\Mapsui.Samples.Uno.WinUI.Mobile.csproj
    - name: Mapsui.Samples.Uno.WinUI.Skia.Gtk
      run: dotnet build --no-restore --configuration Debug Samples\Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Skia.Gtk\Mapsui.Samples.Uno.WinUI.Skia.Gtk.csproj
    - name: Mapsui.Samples.Uno.WinUI.Skia.Linux.FrameBuffer
      run: dotnet build --no-restore --configuration Debug Samples\Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Skia.Linux.FrameBuffer\Mapsui.Samples.Uno.WinUI.Skia.Linux.FrameBuffer.csproj
    - name: Mapsui.Samples.Uno.WinUI.Skia.WPF
      run: dotnet build --no-restore --configuration Debug Samples\Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Skia.WPF\Mapsui.Samples.Uno.WinUI.Skia.WPF.csproj
    - name: Mapsui.Samples.Uno.WinUI.Wasm
      run: dotnet build --no-restore --configuration Debug Samples\Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Wasm\Mapsui.Samples.Uno.WinUI.Wasm.csproj
    - name: Mapsui.Samples.Uno.WinUI.Windows
      run: dotnet build --no-restore --configuration Debug  /p:Platform=x64 Samples\Mapsui.Samples.Uno.WinUI\Mapsui.Samples.Uno.WinUI.Windows\Mapsui.Samples.Uno.WinUI.Windows.csproj
    # Publishing  
    - name: Upload packages
      uses: actions/upload-artifact@v2
      with:
        name: nupkg.win
        path: Artifacts/*.nupkg  
